### ISSUE TITLE
Desahogo / Cierre: orden

### ISSUE THREAD

**Issue by ecristerna** [aledi/pitagoras#101]
Pasar acción en lista después de `Demanda prevenida`

**Comment by acristernam** [comment]
pero no quedamos que no iba a poder desahogar inmediatamente? no tenemos que mejor borrar la acción de desahogo / cierre ?

**Comment by ecristerna** [comment]
va a ser después de hacer lo de `Demanda prevenida`donde se hace un recoradatorio; pero no lo vamos a restringir nosotros
