### ISSUE TITLE
Diligencia de embargo: campos

### ISSUE THREAD

**Issue by ecristerna** [aledi/pitagoras#103]
Agregar opción `Se dejó citatorio` que, si se selecciona, aparece nuevos campos para `Fecha de cita, lugar, nombre del actuario y teléfono del actuario`.

Cualquier otra opción queda como estaba.

**Comment by acristernam** [comment]
@ecristerna un checkbox?

**Comment by ecristerna** [comment]
@alexcris no, es un option del select
