### ISSUE TITLE
Contratos: Get juzgado value

### ISSUE THREAD

**Issue by acristernam** [aledi/pitagoras#120]

**Comment by acristernam** [comment]
@ecristerna este siempre sí va a ir en la tabla de contratos?

**Comment by ecristerna** [comment]
sí, cuando existe

**Comment by acristernam** [comment]
@ecristerna el juzgado sale de la presentación de demanda o del amparo? o de cualquiera de las dos?

**Comment by ecristerna** [comment]
presentación de demanda
