### ISSUE TITLE
Import from Excel

### ISSUE THREAD

**Issue by ecristerna** [aledi/pitagoras#202]
Hay que ver cómo podemos hacer esto. Me pasaron el excel, hay que pensar bien cómo podemos hacerlo. Esto va a ser aparte de lo que teníamos contemplado, pero sí lo necesita y creo que lo podemos hacer.

**Comment by acristernam** [comment]
@ecristerna esto ya no va a ser necesario o sí? quedaron contratos pendientes por agregar?

**Comment by ecristerna** [comment]
no; y sí, faltan 130
