### ISSUE TITLE
Acciones: Fecha audiencia previa

### ISSUE THREAD

**Issue by acristernam** [aledi/pitagoras#239]
Acción para Juicio Oral con campos:
- Atendido por (abierto)
- Fecha y Hora
- Observaciones (abierto)

**Comment by acristernam** [comment]
@ecristerna observaciones puede ser el que ponemos siempre de comentarios?

**Comment by ecristerna** [comment]
@alexcris sí

**Comment by acristernam** [comment]
@ecristerna 

Va algún dato de esta acción en el reporte?
Genera notificación?

**Comment by ecristerna** [comment]
igual que los demás con fecha. notificación de acuerdo a la fecha y el campo en el reporte
