### ISSUE TITLE
Notificaciones para nuevas acciones

### ISSUE THREAD

**Issue by acristernam** [aledi/pitagoras#240]

**Comment by alexcris** [comment]
y fecha de audiencia prueba

**Comment by acristernam** [comment]
Oral:
- [x] Fecha Audiencia Previa
- [x] Fecha Audiencia Pruebas
- [x] Fecha de Sentencia

Ejecutivo:
- [x] Fecha Audiencia Pruebas
- [x] Sentencia de Apelación
- [x] Amparo vs Sentencia

**Comment by acristernam** [comment]
@ecristerna qué textos usamos para las notificaciones? porque por ejemplo para recolección de documentos hay un custom de 'requiere recoger documentos el día...' o para el desahogo.

**Comment by ecristerna** [comment]
`La fecha de` + Nombre de Acción + `es el…`
