### ISSUE TITLE
Acciones: Sentencia

### ISSUE THREAD

**Issue by acristernam** [aledi/pitagoras#246]
Acción para Juicio Oral con campos:
- Favorable a (GMF, Demandado, Tercero)

**Comment by acristernam** [comment]
@ecristerna esto es un select?

**Comment by ecristerna** [comment]
hmm, se puede hacer con radio? y si elige "Tercero" aparezca un campo de texto y se guarda ese valor?

**Comment by acristernam** [comment]
ok

**Comment by acristernam** [comment]
@ecristerna también genera un campo en el reporte?

**Comment by ecristerna** [comment]
lo reviso.
