### ISSUE TITLE
Depuración

### ISSUE THREAD

**Issue by ecristerna** [aledi/pitagoras#283]
@alexcris 👀 

Dos checkbox:
- Depuración Judicial
- Depuración Extrajudicial

Al estar uno marcado, el listado de acciones se pinta de naranja, si ambos están marcados, se pintan de rojo.

Guardar quién hizo la acción (el que está loggeado) y en qué fecha/hora, tanto de marcar como de  desmarcar cualquiera de las dos. (No sé si por esto sí sea mejor separarlo en dos acciones diferentes)

Pedir confirmación (alerta) cuando se marque o desmarque cualquiera de las dos.

Mostrar en el reporte.

**Comment by acristernam** [comment]
qué es esto ? @ecristerna

**Comment by ecristerna** [comment]
la acción que pidieron; pero después lo vemos

**Comment by acristernam** [comment]
ya tienes más detalles de esta acción? @ecristerna
