### ISSUE TITLE
Reportes y Notificaciones sobre info más reciente

### ISSUE THREAD

**Issue by ecristerna** [aledi/pitagoras#284]
No sé cómo esté ahorita, pero la info que aparece en reportes, y las notificaciones que se generan, deben de ser sobre las acciones más reciente de cada tipo. P.e., si hicieron una acción que hizo notificación, y después hicieron otra del mismo tipo (porque se equivocaron), la notificación debería de ser sobre la nueva fecha.

**Comment by acristernam** [comment]
pero y si hace una acción que genera notificación y luego hace otra acción que genera también notificación? cuál debería de quedarse? la más nueva? las dos?

**Comment by ecristerna** [comment]
si es del mismo tipo de acción, la más nueva. si es de otro tipo de acción (que en teoría no debería de pasar por los tiempos) las dos.

**Comment by acristernam** [comment]
@ecristerna sí se guarda la de la fecha más reciente. voy a cerrar este y abrir otro para manejar lo de dos  o más notificaciones por contrato, porque ahorita solo está que tenga una.
