### ISSUE TITLE
Acciones: Liquidación (Extrajudicial)

### ISSUE THREAD

**Issue by acristernam** [aledi/pitagoras#304]
- Radio: Parcial o Total

**Comment by alexcris** [comment]
Acción para Extrajudicial con campos:
- Parcial o Total

**Comment by alexcris** [comment]
@ecristerna es un radio?

**Comment by ecristerna** [comment]
sí; si quieres después te pongo los issues más detallados, primero hay que ver si aprueban la propuesta
