### ISSUE TITLE
Acciones: REPO (Extrajudicial)

### ISSUE THREAD

**Issue by ecristerna** [aledi/pitagoras#306]
- Radio: Voluntario o Contra Finiquito
- Abierto: Valor en libros (Se incluye en reporte extrajudicial)
- Radio: Personal o Apoderado
       - Si Apoderado:
          - Fecha: VoBo RBU
          - Fecha: VoBo GMF
- Fecha: Fecha REPO (Se incluye en reporte extrajudicial)
- Lugar Custodia - Radio: Oficina México o Dealer (mostrar campo abierto)
- Fecha de Subasta: Fechas múltiples
- Abierto: Monto de venta (Se incluye en reporte extrajudicial)
- Fecha: Fecha de Venta (Se incluye en reporte extrajudicial)

**Comment by acristernam** [comment]
@ecristerna Fecha de subasta cómo que fechas múltiples? que pueden agregar varias? hasta cuántas?

**Comment by ecristerna** [comment]
@alexcris sí, 5
