### ISSUE TITLE
Acciones: Emplazamiento (Demanda Admitida)

### ISSUE THREAD

**Issue by ecristerna** [aledi/pitagoras#308]
- Cambiar nombre de acción a Emplazamiento (antes Demanda Admitida)
- Quitar ambas fecha en acción y agregar el campo Fecha de diligencia
- Resultado de Emplazamiento: Quitar opción Exhorto; agregar opción vacía (para que quede por default)

**Comment by acristernam** [comment]
@ecristerna la fecha de la cita y todo lo demás referente a la cita sí se queda? esto cuando es tipoJuicio === 'Ejecutiva Mercantil

**Comment by acristernam** [comment]
@ecristerna también, la fecha de acuerdo era la fecha de admisión del reporte. se va a quitar?
`contrato.reporte.fechaAdmision = accion.respuestas.fechaAcuerdo;`

**Comment by ecristerna** [comment]
así como lo estás haciendo está bien: se quitan estas dos `Fecha de Acuerdo|Publicación` y se pone `Fecha de Diligencia` (no está relacionada con nada de lo anterior). de lo segundo, ya no va a ser, porque `Fecha de Acuerdo` ya no va a existir.

<img width="277" alt="captura de pantalla 2017-04-13 a la s 20 07 56" src="https://cloud.githubusercontent.com/assets/3680271/25030824/16743b60-2085-11e7-831c-048d0231fc09.png">
